version: '3'

services:
  quarkus-service:
    image: quarkus/gateway-jvm
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8088:8081"
    networks:
      - auth-network
    env_file:
      - .env      
    depends_on:
      - dbapp
      - keycloak
      - minio
  dbapp:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - auth-network
    ports:
      - "3306:3306"
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - auth-network
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: dbk-keycloak
    hostname: keycloak
    env_file:
      - .env
    ports:
      - "8180:8080"
    depends_on:
      - postgres
    networks:
      - auth-network
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ~/minio/data:/data
    networks:
      - auth-network
    env_file:
      - .env
    command: server /data --console-address ":9090"
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    env_file:
      - .env
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    networks:
      - auth-network
  krakend:
    image: devopsfaith/krakend:2.0.6
    ports:
      - "9091:9091"
      - "8085:8080"
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  mysql_data:
    driver: local