apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter
spec:
  selector:
    matchLabels:
      app: conveter
  template:
    metadata:
      labels:
        app: conveter
    spec:
      containers:
      - name: gateway
        image: thomazfsj/gateway-mp4tomp3:0.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: converter
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
  - port: 8080
    targetPort: 8080
